In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
df = pd.read_csv('../data/preprocessed_Lubusz_data.csv', index_col=0)

df.head()

,station_code,station_name,24h_precipitation_mm,SMDB_status,precip_type,snow_cover_cm,river,lat,lon,altitude
date,,,,,,,,,,
1991-01-01,251150110,ŻAGAŃ,1.9,Normal,Water,0.0,Bóbr,51.649722,15.293611,96.0
1991-01-02,251150110,ŻAGAŃ,2.5,Normal,Water,0.0,Bóbr,51.649722,15.293611,96.0
1991-01-03,251150110,ŻAGAŃ,1.1,Normal,Water,0.0,Bóbr,51.649722,15.293611,96.0
1991-01-04,251150110,ŻAGAŃ,3.2,Normal,Water,0.0,Bóbr,51.649722,15.293611,96.0
1991-01-05,251150110,ŻAGAŃ,1.3,Normal,Water,0.0,Bóbr,51.649722,15.293611,96.0

In [27]:
def calculate_SPI(df):
    precip_sum = df['24h_precipitation_mm']
    params = stats.gamma.fit(precip_sum, floc=0)
    shape, loc, scale = params
    cdf = stats.gamma.cdf(precip_sum, shape, loc, scale)
    SPI = stats.norm.ppf(cdf)
    return pd.DataFrame({"SPI":SPI},index=df.index)

df.index = pd.to_datetime(df.index)

SPI_1Y = df.resample('YE').agg({"24h_precipitation_mm":'sum}').dropna()  
SPI_1 = calculate_SPI(SPI_1Y)

SPI_3M = df.resample('QE').sum().dropna()  
SPI_3 = calculate_SPI(SPI_3M)

SPI_1M = df.resample('ME').sum().dropna() 
SPI_12 = calculate_SPI(SPI_1M)

In [16]:
print(len(df),len(SPI_1),len(SPI_3),len(SPI_12))

23099 32 128 384